### ISSUE TITLE
新版本报错了

### ISSUE THREAD

**Issue by miniers** [oldweipro/claude-to-chatgpt#3]
更新完今天的代码就报这个错了😂

[GIN-debug] Listening and serving HTTP on :8787
Unmarshal err: json: cannot unmarshal object into Go value of type []model.OrganizationsResponse
[GIN] 2023/07/29 - 11:54:12 | 500 |  159.984725ms |       10.10.0.3 | POST     "/v1/chat/completions"

**Comment by onepy** [comment]
你是使用了多个key值？

如果是的话，需要检查你的每个session-key值是否有效，无法获取组织id响应通常是你退出网页后cookie失效导致。

**Comment by oldweipro** [comment]
我做了一期视频，可以看一下，希望对你们有帮助。

[开发教程](https://www.bilibili.com/video/BV1DV4y1q7Dp/?vd_source=239ca057ded009574befe2b4e513d6a3)

**Comment by onepy** [comment]
> 我做了一期视频，可以看一下，希望对你们有帮助。
> 
> [开发教程](https://www.bilibili.com/video/BV1DV4y1q7Dp/?vd_source=239ca057ded009574befe2b4e513d6a3)

感谢解答，还有就是如果你询问一些敏感问题，claude受到风控后（官网顶部黄色监控标识），即使你的sessionkey可以用，也是会500报错的

**Comment by miniers** [comment]
问题找到了，配置文件里 session-keys 这个key变了🤣，原来没有最后的这个s，更新后没注意到
