### ISSUE TITLE
Sesion key的相关问题

### ISSUE THREAD

**Issue by Hell2023** [oldweipro/claude-to-chatgpt#4]
如果我自己写的项目发送的时候带了api key，那我是不是不用在config文件里面去配置api？我现在两端都配置了。如果config不用配置那我就可以去掉了。我自己的项目又key池。

**Comment by Hell2023** [comment]
我研究一下

**Comment by Hell2023** [comment]
请求传递了API，确实可以不用配置config里面的key。

**Comment by oldweipro** [comment]
> 请求传递了API，确实可以不用配置config里面的key。

😂你是怎么做的，我还没有做适配[authentication](https://platform.openai.com/docs/api-reference/authentication)

**Comment by oldweipro** [comment]
> 可以兼容一下[authentication](https://platform.openai.com/docs/api-reference/authentication)，是否能解决你的需求。

- 我推送了Authentication的支持
