### ISSUE TITLE
关于上传附件的功能

### ISSUE THREAD

**Issue by Hell2023** [oldweipro/claude-to-chatgpt#5]
能不能做个适配？看目前好像是没有这个功能

**Comment by oldweipro** [comment]
主要目的是为了兼容[ChatGPT的接口标准](https://platform.openai.com/docs/api-reference/chat/create)，文档中没有这个附件功能，所以我也没做附件的功能。

**Comment by oldweipro** [comment]
关于**附件功能**，**我的方案**

 在ChatGPT标准接口增加一个`附件参数`，如果不传`附件参数`也不影响原有接口的使用。
 
 有更好的方案欢迎讨论👏

**Comment by onepy** [comment]
一个题外话，chatgpt转换claude后这个附件post参数attachments = []还在留空吗？我发现他们给claude穿甲破限时，prompt都是以附件形式上传对话上下文，这样好像不容易让claude监管，也就能和chatGPT一样实现DAN交流，现在的转换方式还是太容易被claude监管发现了，或许有更好的解决方案？

**Comment by oldweipro** [comment]
> 一个题外话，chatgpt转换claude后这个附件post参数attachments = []还在留空吗？我发现他们给claude穿甲破限时，prompt都是以附件形式上传对话上下文，这样好像不容易让claude监管，也就能和chatGPT一样实现DAN交流，现在的转换方式还是太容易被claude监管发现了，或许有更好的解决方案？

是的，你的提议非常好，attachments作为上下文传递是非常合适的选择；我之前有一种想法是能否像提示词那样把上下文优雅的传递进去，但是做起来好像很麻烦的样子。目前看来attachments传递上下文合适👍。

**Comment by oldweipro** [comment]
> 一个题外话，chatgpt转换claude后这个附件post参数attachments = []还在留空吗？我发现他们给claude穿甲破限时，prompt都是以附件形式上传对话上下文，这样好像不容易让claude监管，也就能和chatGPT一样实现DAN交流，现在的转换方式还是太容易被claude监管发现了，或许有更好的解决方案？

我更新了部分代码，[用attachments传递上下文](https://github.com/oldweipro/claude-to-chatgpt/commit/d75df6448f0d8e03c0df1960ec15d388440c74d8)，上下文过多，超出单个attachment的限制暂时没做判断，在我有更好的方案时会去补全，如果你有更好的方案欢迎PR。

**Comment by onepy** [comment]
> > 一个题外话，chatgpt转换claude后这个附件post参数attachments = []还在留空吗？我发现他们给claude穿甲破限时，prompt都是以附件形式上传对话上下文，这样好像不容易让claude监管，也就能和chatGPT一样实现DAN交流，现在的转换方式还是太容易被claude监管发现了，或许有更好的解决方案？
> 
> 我更新了部分代码，[用attachments传递上下文](https://github.com/oldweipro/claude-to-chatgpt/commit/d75df6448f0d8e03c0df1960ec15d388440c74d8)，上下文过多，超出单个attachment的限制暂时没做判断，在我有更好的方案时会去补全，如果你有更好的方案欢迎PR。

高产的老卫👍，很不好意思的是我的编程能力有限😅，不过有好的想法和提议我会持续向你交流的，哈哈

**Comment by oldweipro** [comment]
> > > 一个题外话，chatgpt转换claude后这个附件post参数attachments = []还在留空吗？我发现他们给claude穿甲破限时，prompt都是以附件形式上传对话上下文，这样好像不容易让claude监管，也就能和chatGPT一样实现DAN交流，现在的转换方式还是太容易被claude监管发现了，或许有更好的解决方案？
> > 
> > 
> > 我更新了部分代码，[用attachments传递上下文](https://github.com/oldweipro/claude-to-chatgpt/commit/d75df6448f0d8e03c0df1960ec15d388440c74d8)，上下文过多，超出单个attachment的限制暂时没做判断，在我有更好的方案时会去补全，如果你有更好的方案欢迎PR。
> 
> 高产的老卫👍，很不好意思的是我的编程能力有限，不过有好的想法和提议我会持续向你交流的，哈哈

非常感谢你的提议和想法💡一起交流进步。
