### ISSUE TITLE
这样适配完成后，有没有可能替代AutoGPT中的ChatGPT4呢？

### ISSUE THREAD

**Issue by minex2** [oldweipro/claude-to-chatgpt#6]
有没有可能通过这样的适配，使用Claude2来替代AutoGPT中的ChatGPT4呢？如果可以的话，那项目能够运用的地方就多了。

**Comment by oldweipro** [comment]
GitHub中很多基于ChatGPT标准接口开发的项目，都可以无缝切换到这个项目接口上，但是有一点，这个项目的可选参数并不多，仅仅只是prompt的输入输出。

**Comment by oldweipro** [comment]
比如function calling就用不上了。
