### ISSUE TITLE
大佬你好~使用dock run似乎无法部署，出现报错

### ISSUE THREAD

**Issue by zisanjun** [oldweipro/claude-to-chatgpt#7]
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3997275693/Dockerfile: no such file or directory

**Comment by zisanjun** [comment]
镜像为私有镜像，需要输入dockerhub的账号密码

**Comment by zisanjun** [comment]
应该是这个原因，大佬你有空了看看~

**Comment by oldweipro** [comment]
我没有提供打包好的公共镜像，你需要把项目代码拉下来，在项目中构建镜像，然后运行镜像。**注意**修改配置文件中的key，否则无法正常使用。

**Comment by zisanjun** [comment]
明白 感谢

**Comment by oldweipro** [comment]
> 镜像为私有镜像，需要输入dockerhub的账号密码

[开发教程](https://www.bilibili.com/video/BV1DV4y1q7Dp/?vd_source=239ca057ded009574befe2b4e513d6a3) 在这个视频的末尾有讲docker运行

**Comment by zisanjun** [comment]
感恩！我再仔细学习一下

**Comment by zisanjun** [comment]
特别好用！感谢！！
